[versions]
accompanist = "0.28.0"
activity-compose = "1.6.1"
androidx-lifecycle = "2.5.1"
apollo = "3.7.4"
compose = "1.4.0-alpha04"
compose-compiler = "1.4.0-dev-k1.8.0-RC-4c1865595ed"
compose-material-3 = "1.0.0"
junit = "4.13"
kmp-nativecoroutines = "1.0.0-ALPHA-3"
kmm-viewmodel = "1.0.0-ALPHA-3"
koin-android = "3.3.1"
koin-android-compose = "3.4.0"
koin-core = "3.3.0"
kotlin = "1.8.0"
kotlin-coroutines = "1.6.4"
kotlinx-datetime = "0.4.0"
lifecycle = "2.6.0-alpha03"
multiplatform-settings = "1.0.0"
nav-compose = "2.5.2"

[libraries]
accompanist-adaptive = { module = "com.google.accompanist:accompanist-adaptive", version.ref = "accompanist" }
accompanist-flow-layout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
apollo-adapters = { module = "com.apollographql.apollo3:apollo-adapters" }
apollo-normalized-cache-in-memory = { module = "com.apollographql.apollo3:apollo-normalized-cache" }
apollo-normalized-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime" }
apollo-tooling = { module = "com.apollographql.apollo3:apollo-tooling", version.ref = "apollo" }
bare-graphQL = "net.mbonnin.bare-graphql:bare-graphql:0.0.2"
coil-base = "io.coil-kt:coil-base:2.2.2"
coil-compose = "io.coil-kt:coil-compose:2.2.2"
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-core = { module = "androidx.compose.material:material-icons-core", version.ref = "compose" }
compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "nav-compose" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
google-cloud-datastore = "com.google.cloud:google-cloud-datastore:2.11.0"
graphql-kotlin-spring-server = "com.expediagroup:graphql-kotlin-spring-server:6.3.3"
graphql-java = "com.graphql-java:graphql-java:20.0"
junit = "junit:junit:4.13.2"
kaml = "com.charleskorn.kaml:kaml:0.47.0"
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-core" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin-core" }
kmm-viewmodel = { module = "com.rickclephas.kmm:kmm-viewmodel-core", version.ref = "kmm-viewmodel" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2"
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlin-coroutines" }
ktor-cio = "io.ktor:ktor-server-cio:2.1.0"
ktor-status-pages = "io.ktor:ktor-server-status-pages:2.1.0"
lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
material3-core = { module = "androidx.compose.material3:material3", version.ref = "compose-material-3" }
material3-window-size = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "compose-material-3" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatform-settings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatform-settings" }
okhttp = "com.squareup.okhttp3:okhttp:5.0.0-alpha.11"
okhttp-coroutines = "com.squareup.okhttp3:okhttp-coroutines:5.0.0-alpha.11"
okhttp-logging-interceptor = "com.squareup.okhttp3:logging-interceptor:5.0.0-alpha.11"
reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
splash-screen = "androidx.core:core-splashscreen:1.0.0"
xoxo = "net.mbonnin.xoxo:xoxo:0.2"
desugar = "com.android.tools:desugar_jdk_libs:2.0.0"
wear-compose-material = "androidx.wear.compose:compose-material:1.2.0-alpha02"
wear-compose-navigation = "androidx.wear.compose:compose-navigation:1.2.0-alpha02"
horologist-base-ui = "com.google.android.horologist:horologist-base-ui:0.2.7"
horologist-compose-layout = "com.google.android.horologist:horologist-compose-layout:0.2.7"
horologist-compose-tools = "com.google.android.horologist:horologist-compose-tools:0.2.7"
horologist-composables = "com.google.android.horologist:horologist-composables:0.2.7"
horologist-tiles = "com.google.android.horologist:horologist-tiles:0.2.7"
wear-complications-data = "androidx.wear.watchface:watchface-complications-data-source-ktx:1.1.1"

[bundles]
multiplatform-settings = ["multiplatform-settings", "multiplatform-settings-coroutines"]
apollo = ["apollo-normalized-cache-in-memory", "apollo-normalized-cache-sqlite", "apollo-adapters"]

[plugins]
android-application = { id = "com.android.application", version = "7.4.0" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
appengine = { id = "com.google.cloud.tools.appengine", version = "2.4.5" }
kmmbridge = { id = "co.touchlab.faktory.kmmbridge", version = "0.3.1" }
kmp-nativecoroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "kmp-nativecoroutines" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version = "1.8.0-1.0.8" }
spring-boot = { id = "org.springframework.boot", version = "2.5.6" }